import { CountryConfig } from "./types";

export const COUNTRIES: CountryConfig[] = [
  {
    name: "Nigeria",
    code: "NG",
    currencyCode: "NGN",
    currencySymbol: "₦",
    flag: "🇳🇬",
    exchangeRate: 1550,
    deliveryMethods: ["Bank Transfer"],
    banks: ["Access Bank", "GTBank", "Zenith Bank", "First Bank"],
  },
  {
    name: "Kenya",
    code: "KE",
    currencyCode: "KES",
    currencySymbol: "KSh",
    flag: "🇰🇪",
    exchangeRate: 130,
    deliveryMethods: ["M-Pesa", "Bank Transfer"],
    banks: ["KCB", "Equity Bank"],
  },
  {
    name: "Ghana",
    code: "GH",
    currencyCode: "GHS",
    currencySymbol: "GH₵",
    flag: "🇬🇭",
    exchangeRate: 15.8,
    deliveryMethods: ["MTN Mobile Money", "Vodafone Cash", "Bank Transfer"],
    banks: ["GCB", "Ecobank"],
  },
  {
    name: "South Africa",
    code: "ZA",
    currencyCode: "ZAR",
    currencySymbol: "R",
    flag: "🇿🇦",
    exchangeRate: 18.2,
    deliveryMethods: ["Bank Transfer"],
    banks: ["FNB", "Standard Bank", "Nedbank", "Capitec"],
  },
  {
    name: "Ethiopia",
    code: "ET",
    currencyCode: "ETB",
    currencySymbol: "ETB",
    flag: "🇪🇹",
    exchangeRate: 127,
    deliveryMethods: ["Bank Transfer"],
    banks: ["CBE", "Dashen Bank"],
  },
  {
    name: "Uganda",
    code: "UG",
    currencyCode: "UGX",
    currencySymbol: "UGX",
    flag: "🇺🇬",
    exchangeRate: 3750,
    deliveryMethods: ["Airtel Money", "MTN Mobile Money", "Bank Transfer"],
    banks: ["Stanbic Uganda", "Centenary Bank"],
  },
  {
    name: "Tanzania",
    code: "TZ",
    currencyCode: "TZS",
    currencySymbol: "TZS",
    flag: "🇹🇿",
    exchangeRate: 2650,
    deliveryMethods: ["M-Pesa", "Airtel Money", "Bank Transfer"],
    banks: ["CRDB", "NMB"],
  },
];

export const COUNTRY_MAP = Object.fromEntries(
  COUNTRIES.map((c) => [c.name, c])
) as Record<string, CountryConfig>;

export const COMPETITOR_COMPARISON = [
  {
    feature: "Cost per $1,000",
    remora: "$15",
    deel: "$49",
    wise: "$25",
    payoneer: "$30",
    wire: "$45-80",
  },
  {
    feature: "Speed",
    remora: "< 1 hour",
    deel: "1-3 days",
    wise: "1-2 days",
    payoneer: "2-5 days",
    wire: "3-5 days",
  },
  {
    feature: "Mobile Money",
    remora: "Yes",
    deel: "No",
    wise: "Limited",
    payoneer: "No",
    wire: "No",
  },
  {
    feature: "Contractor Mgmt",
    remora: "Yes",
    deel: "Yes",
    wise: "No",
    payoneer: "No",
    wire: "No",
  },
  {
    feature: "Bulk Pay",
    remora: "Yes",
    deel: "Yes",
    wise: "Limited",
    payoneer: "Yes",
    wire: "No",
  },
  {
    feature: "Invoicing",
    remora: "Yes",
    deel: "Yes",
    wise: "No",
    payoneer: "Yes",
    wire: "No",
  },
];

export const PRICING_TIERS = [
  {
    name: "Starter",
    price: "1.5%",
    priceDetail: "per transaction",
    monthly: "Free",
    description: "For teams just getting started with African contractors",
    features: [
      "Up to 10 contractors",
      "All 7 country corridors",
      "M-Pesa & Mobile Money",
      "Basic reporting",
      "Email support",
    ],
    cta: "Start Free",
    highlighted: false,
  },
  {
    name: "Growth",
    price: "1%",
    priceDetail: "per transaction",
    monthly: "$49/mo",
    description: "For growing teams scaling their African workforce",
    features: [
      "Up to 50 contractors",
      "All 7 country corridors",
      "M-Pesa & Mobile Money",
      "Advanced analytics",
      "Bulk payroll",
      "Priority support",
      "API access",
    ],
    cta: "Start Saving",
    highlighted: true,
  },
  {
    name: "Enterprise",
    price: "Custom",
    priceDetail: "volume-based",
    monthly: "Custom",
    description: "For large organizations with complex payroll needs",
    features: [
      "Unlimited contractors",
      "Custom corridors",
      "Dedicated account manager",
      "Custom integrations",
      "SLA guarantees",
      "SOC 2 audit reports",
    ],
    cta: "Contact Sales",
    highlighted: false,
  },
];
